#   _____      ____     ______       ____       __    __        __      _    _____    _____   ________    _____     ____  
#  (  __ \    (    )   (   __ \     (    )      \ \  / /       /  \    / )  / ___/   / ____\ (___  ___)  (_   _)   / ___) 
#   ) )_) )   / /\ \    ) (__) )    / /\ \      () \/ ()      / /\ \  / /  ( (__    ( (___       ) )       | |    / /     
#  (  ___/   ( (__) )  (    __/    ( (__) )     / _  _ \      ) ) ) ) ) )   ) __)    \___ \     ( (        | |   ( (      
#   ) )       )    (    ) \ \  _    )    (     / / \/ \ \    ( ( ( ( ( (   ( (           ) )     ) )       | |   ( (      
#  ( (       /  /\  \  ( ( \ \_))  /  /\  \   /_/      \_\   / /  \ \/ /    \ \___   ___/ /     ( (       _| |__  \ \___  
#  /__\     /__(  )__\  )_) \__/  /__(  )__\ (/          \) (_/    \__/      \____\ /____/      /__\     /_____(   \____) 
#                                                                                                                     
#
# Version of this config. Please do not change.
configVersion: maven-config-version
#Prunt's restricedCreative is the only creative manager supported at this time.
creativeManager: 'restrictedCreative'
#Intelli's coreProtect is the only block logger supported at this time.
#Note! Paramnestic does NOT yet support creative inventory rollbacks!
#Please ensure that any such features are disabled in your blocklogger.
blockLogger: 'coreProtect'
blockLoggerCommands:
   alias:
       - co
       - core
       - coreprotect
       - coreprotect:co
       - coreprotect:core
       - coreprotect:coreprotect
   rollback:
       - rollback
       - rb
   restore:
       - restore
       - rs
   undo:
       - undo
   purge:
       - purge
   help:
       - help
   arguments:
      time:
          - t
          - time
      radius:
          - r
          - radius
          - area
      user:
          - u
          - user
          - player
      action:
          - a
          - action
      exclude:
          - e
          - exclude
      block:
          - b
          - block
# The permessions for the blocklogger
blockLoggerPermissions:
   rollback: coreprotect.rollback
   purge: coreprotect.purge
   restore: coreprotect.restore
   help: coreprotect.help

# All database config for the database of paramnestic
Database:
  # Database type
  driver: Sqlite
  # Database location
  address: localhost
  # Port used by your db.
  port: 3306
  # The name for the database
  databasename: "paramnestic"
