#   _____      ____     ______       ____       __    __        __      _    _____    _____   ________    _____     ____  
#  (  __ \    (    )   (   __ \     (    )      \ \  / /       /  \    / )  / ___/   / ____\ (___  ___)  (_   _)   / ___) 
#   ) )_) )   / /\ \    ) (__) )    / /\ \      () \/ ()      / /\ \  / /  ( (__    ( (___       ) )       | |    / /     
#  (  ___/   ( (__) )  (    __/    ( (__) )     / _  _ \      ) ) ) ) ) )   ) __)    \___ \     ( (        | |   ( (      
#   ) )       )    (    ) \ \  _    )    (     / / \/ \ \    ( ( ( ( ( (   ( (           ) )     ) )       | |   ( (      
#  ( (       /  /\  \  ( ( \ \_))  /  /\  \   /_/      \_\   / /  \ \/ /    \ \___   ___/ /     ( (       _| |__  \ \___  
#  /__\     /__(  )__\  )_) \__/  /__(  )__\ (/          \) (_/    \__/      \____\ /____/      /__\     /_____(   \____) 
#                                                                                                                     
#
# Version of this config. Please do not change.
configVersion: maven-config-version
#Prunt's restricedCreative is the only creative manager supported at this time.
creativeManager: 'restrictedCreative'
#Intelli's coreProtect is the only block logger supported at this time.
blockLogger: 'coreProtect'
blockLoggerRollbackCommands:
    - co rollback
    - core rollback
    - coreprotect rollback
    - co rb
    - core rb
    - coreprotect rb
    - coreprotect:co rollback
    - coreprotect:core rollback
    - coreprotect:coreprotect rollback
    - coreprotect:co rb
    - coreprotect:core rb
    - coreprotect:coreprotect rb
    - co restore
    - core restore
    - coreprotect restore
    - co rs
    - core rs
    - coreprotect rs
    - coreprotect:co restore
    - coreprotect:core restore
    - coreprotect:coreprotect restore
    - coreprotect:co rs
    - coreprotect:core rs
    - coreprotect:coreprotect rs
# Default information used when a value in Database_Names is blank ("")
# Please ensure that all three of the databases you intend to use have already been configured by your logger and creative manager.
defaultconnection:
  # Database type
  driver: Sqlite
  # Database location
  address: localhost
  # Port used by your db.
  port: 3306
  # Username with which to connect to the db.
  user: 'root'
  # Password for that username.
  password: 'pass'
# Databases for us to send specific requests to.
# Paramnestic requires all three databases to be running, set up, and seperate to function.
Database_Names:
    # The database for Paramnestic to send requests related to creative block protection
    # (Your creative manager)
    creative:
        database: "creative"
        driver: ""
        address: ""
        port: ""
        user: ""
        password: ""
    # The database for Paramnestic to send requests related to general block logging
    # (Your block logger)
    logger:
        database: "coreprotect"
        driver: ""
        address: ""
        port: ""
        user: ""
        password: ""
    # The database for Paramnestic to store its own data.
    # (ParamnesticCure)
    paramestic:
        database: "paramnestic"
        driver: ""
        address: ""
        port: ""
        user: ""
        password: ""