#   _____      ____     ______       ____       __    __        __      _    _____    _____   ________    _____     ____  
#  (  __ \    (    )   (   __ \     (    )      \ \  / /       /  \    / )  / ___/   / ____\ (___  ___)  (_   _)   / ___) 
#   ) )_) )   / /\ \    ) (__) )    / /\ \      () \/ ()      / /\ \  / /  ( (__    ( (___       ) )       | |    / /     
#  (  ___/   ( (__) )  (    __/    ( (__) )     / _  _ \      ) ) ) ) ) )   ) __)    \___ \     ( (        | |   ( (      
#   ) )       )    (    ) \ \  _    )    (     / / \/ \ \    ( ( ( ( ( (   ( (           ) )     ) )       | |   ( (      
#  ( (       /  /\  \  ( ( \ \_))  /  /\  \   /_/      \_\   / /  \ \/ /    \ \___   ___/ /     ( (       _| |__  \ \___  
#  /__\     /__(  )__\  )_) \__/  /__(  )__\ (/          \) (_/    \__/      \____\ /____/      /__\     /_____(   \____) 
#                                                                                                                     
#
#Last version of plugin used.
configVersion: 5
#Prunt's restricedCreative is the only creative manager supported at this time.
creativeManager: 'restrictedCreative'
#Intelli's coreProtect is the only block logger supported at this time.
blockLogger: 'coreProtect'
blockLoggerRollbackCommands:
    - co rollback
    - core rollback
    - coreprotect rollback
    - co rb
    - core rb
    - coreprotect rb
    - coreprotect:co rollback
    - coreprotect:core rollback
    - coreprotect:coreprotect rollback
    - coreprotect:co rb
    - coreprotect:core rb
    - coreprotect:coreprotect rb
databases:
  # MySQL and MariaDB are supported database drivers at this time.
  driver: Sqlite
  # Database server address.
  address: localhost
  # Database port
  port: 3306
  # Database username
  username: 'root'
  # Database user password
  password: 'pass'
  # Creative database
  creative:
    # Database used by restrictedCreative
    database: 'creative'
    # Table of that database where RC stores its block data.
    table: 'rc_blocks'
  logger:
    # Database used by coreProtect
    database: 'coreprotect'
    # Table of that database where CP stores its block data.
    table: 'co_block'
    # Table of that database where CP stores its world data.
    world_table: 'co_world'
  paramnestic:
    # Name of the database that you would like Paramnestic to use.
    database: 'paramnestic'